[feature][APPH-220]: set up a map for photos
mgermanicus/apph pull request #114
Opened 2022-07-22 09:26 UTC by MOMney

2022-07-25 08:11 UTC, Ravassee requested changes

2022-07-25 08:11 UTC, Ravassee commented on apph-front/src/static/pages/MapPage.tsx
> +      <h1>Photo Map</h1>
Ce titre est assez moche (il est au dessus de la carte avec un gros espace blanc, et il ne sert pas à grand chose)... Tu pourrais peut être l'intégrer directement dans la carte ? Ou alors rendre l'espace inutile un peu plus joli, pour pas que ça soit gênant ?

2022-07-25 08:11 UTC, Ravassee commented on apph-front/src/static/components/PhotosMap.tsx
> +      defaultCenter={[locations[0].lat, locations[0].lng]}
Je ne sais pas si c'est du à ce paramètre, mais la carte est par défaut zoomée sur un des pings. Il faudrait plutôt que par défaut elle soit dézoomé en fonction des pings, pour qu'on ai une vision globale de notre carte.

2022-07-25 08:11 UTC, Ravassee commented on apph-front/src/static/pages/MapPage.tsx
> +];
Supprime ces deux points, je suppose que ce sont des tests

2022-07-25 13:15 UTC, Ravassee approved these changes

2022-07-26 08:39 UTC, wassim-viseo approved these changes

2022-07-26 08:40 UTC, merged