Feature/apph 35 user profile
mgermanicus/apph pull request #12
Opened 2022-04-15 15:14 UTC by MOMney

2022-04-25 15:44 UTC, alexandre-hu requested changes

2022-04-25 15:44 UTC, alexandre-hu commented on apph-back/src/test/java/com/viseo/apph/UserTest.java
> +        when(typedQuery.setParameter("login", user.getLogin())).thenThrow(noResultException);
```suggestion
        when(typedQuery.setParameter("login", user.getLogin())).thenReturn(typedQuery);
        when(typedQuery.getSingleResult()).thenThrow(new NoResultException());
```

2022-04-25 15:44 UTC, alexandre-hu commented on apph-back/src/test/java/com/viseo/apph/UserTest.java
> +        when(typedQuery.setParameter("login", user.getLogin())).thenThrow(noResultException);
```suggestion
```

2022-04-25 15:44 UTC, alexandre-hu commented on apph-back/src/test/java/com/viseo/apph/UserTest.java
> +        when(typedQuery.setParameter("login", "toto")).thenThrow(expiredJwtException);
Presque sûre à 100% que ce n'est pas hibernate qui throw `expiredJwtException`
Je pense qu'il y a un test a faire coté Service pour vérifier si le token est encore valide

2022-04-25 15:44 UTC, alexandre-hu commented on apph-back/src/test/java/com/viseo/apph/UserTest.java
> +    ExpiredJwtException expiredJwtException;
Normalement il n'y a pas besoin de mocker les Exceptions

2022-04-25 15:44 UTC, alexandre-hu commented on apph-back/src/test/java/com/viseo/apph/UserTest.java
> +        when(typedQuery.setParameter("login", "toto")).thenThrow(signatureException);
De même ici, presque sûre à 100% que ce n'est pas hibernate qui throw `signatureException`
Je pense qu'il y a un test a faire coté Service pour vérifier la signature du token

2022-04-26 08:07 UTC, alexandre-hu approved these changes

2022-04-26 13:26 UTC, Ravassee commented on apph-back/src/main/java/com/viseo/apph/controller/UserController.java
> +    public ResponseEntity getUserInfo(@RequestHeader("Authentication") String token, @PathVariable("login") String login) {
le login est contenu dans le token, normalement tu n'as pas à l'envoyer dans la requête (il est dans les claims que tu décomposes en dessous

2022-04-26 13:26 UTC, Ravassee commented on apph-back/src/main/java/com/viseo/apph/service/UserService.java
> +        if (claims.get("login").equals(login))
Je ne comprends pas trop l'intérêt de ce test, dans quel cas le login que tu envoies pourrait-être différent du login dans le token ?

2022-04-26 13:26 UTC, Ravassee commented on apph-front/src/index.tsx
> +if (el === null) throw new Error('Root container missing in index.html');
ça n'arrive jamais, je pense que tu peux laisser le `// eslint-disable-next-line @typescript-eslint/no-non-null-assertion`, sauf si tu trouves ce test pertinent (je t'invite à regarder https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis)

2022-04-26 13:26 UTC, Ravassee commented on apph-front/src/privateRoutes.tsx
> +      <Route path="/me" element={<UserProfileContainer />} />
Je te conseil d'ajouter des `exact` quand tu veux une url précise 
```suggestion
      <Route exact path="/login" element={<SignIn />} />
      <Route exact path="/me" element={<UserProfileContainer />} />
```

2022-04-26 13:26 UTC, Ravassee commented on apph-front/src/services/UserService.ts
> +    const { login, ...token } = cookies.get('user');
Tu pourrais mettre ça au dessus de la classe, pour que ça soit accessible dans tout le fichier nous en aurons besoin quasiment partout).

Par contre je déconseille le spread operator ici, si jamais on ajoute d'autres éléments dans le cookie on ne veut pas qu'ils soient dans la constante `token`

2022-04-26 13:26 UTC, Ravassee commented on apph-front/src/services/UserService.ts
> +    );
Tu peux lui passer directement tes fonctions je pense
```suggestion
 return Server.request(
      `${API_URL}/user/${login}`,
      requestOptions,
      handleSuccess,
      handleError
    );
```

2022-04-26 13:26 UTC, Ravassee commented on apph-front/src/tests/components/Header.test.tsx
> +    render(<Header isAuth={true} />, { wrapper: MemoryRouter });
Pourquoi est-ce que tu as besoin d'un wrapper pour ce test ?

2022-04-26 13:34 UTC, MOMney commented on apph-front/src/privateRoutes.tsx
> +      <Route path="/me" element={<UserProfileContainer />} />
y a plus besoin de 'exact' dans la version v6 du react route

2022-04-26 13:40 UTC, MOMney commented on apph-front/src/tests/components/Header.test.tsx
> +    render(<Header isAuth={true} />, { wrapper: MemoryRouter });
à cause du useHref() (<link /me>), on doit mock un router

2022-04-26 13:57 UTC, MOMney commented on apph-front/src/services/UserService.ts
> +    const { login, ...token } = cookies.get('user');
il va être undefined puisqu'il est défini dans la fonction signIn()

2022-04-26 14:11 UTC, Ravassee commented on apph-front/src/services/UserService.ts
> +    const { login, ...token } = cookies.get('user');
Qu'est-ce qui sera undefined ? De ce que je comprends de ton code, le login sera bien stocké dans login, mais tous les champs restants de ton objet seront stockés dans une variable 'token'

2022-04-26 14:12 UTC, Ravassee approved these changes

2022-04-26 14:15 UTC, alexandre-hu approved these changes

2022-04-26 15:05 UTC, merged