Feature/apph 9 visualisation photos
mgermanicus/apph pull request #24
Opened 2022-04-29 13:32 UTC by wassim-viseo

2022-04-29 14:16 UTC, alexandre-hu commented on apph-back/src/main/java/com/viseo/apph/controller/AuthController.java
> +            String jws = Jwts.builder().claim("login", user.getLogin()).claim("id",user.getId()).setExpiration(new Date(System.currentTimeMillis() + 7_200_000)).signWith(key).compact();
On n'avait pas dit qu'on ne mettait pas l'id du user dans le token ?
Faudra refacto certaine de tes fonctions si on ne le met pas.

2022-04-29 14:16 UTC, alexandre-hu commented on apph-back/src/main/java/com/viseo/apph/controller/PhotoController.java
> +    static TokenManager tokenManager = new TokenManager() {};
Cette interface devrait pas être mit dans un fichier à part ?

2022-04-29 14:16 UTC, alexandre-hu commented on apph-back/src/main/java/com/viseo/apph/security/WebSecurityConfig.java
> +              //  .antMatcher("/photo/**")
pourquoi en commentaire ?

2022-04-29 14:16 UTC, alexandre-hu commented on apph-front/src/services/ImageService.ts
> +const API_URL = process.env['REACT_APP_API_URL'];
Comme je l'avais expliquer l'API_URL sera dans le Server.ts en tant que BASE_API_URL

2022-04-29 14:16 UTC, alexandre-hu commented on apph-front/src/services/TableService.tsx
> +const API_URL = process.env['REACT_APP_API_URL'];
Comme je l'avais expliquer l'API_URL sera dans le Server.ts en tant que BASE_API_URL

2022-04-29 15:35 UTC, Ravassee commented on apph-back/src/main/java/com/viseo/apph/controller/AuthController.java
> +            String jws = Jwts.builder().claim("login", user.getLogin()).claim("id",user.getId()).setExpiration(new Date(System.currentTimeMillis() + 7_200_000)).signWith(key).compact();
Normalement on doit mettre même tout le user dans le token : id, nom, prenom et adresse email

2022-04-29 15:35 UTC, Ravassee commented on apph-back/src/main/java/com/viseo/apph/controller/PhotoController.java
> +    public interface TokenManager{
cette interface devrait aussi permettre de créer/vérifier un token je pense

2022-04-29 15:35 UTC, Ravassee commented on apph-back/src/main/java/com/viseo/apph/service/PhotoService.java
> +                    .setUrl("fake url"); //TODO RECUPERER LE VRAI URL
J'ai envie de mourir

2022-04-29 15:35 UTC, Ravassee commented on apph-back/src/test/java/com/viseo/apph/controller/PhotoControllerTest.java
>      }
Pourquoi avoir enlevé ce test ?

2022-04-29 15:35 UTC, Ravassee commented on apph-back/src/test/java/com/viseo/apph/service/PhotoServiceTest.java
> -    }
Pourquoi avoir enlevé ce test ?

2022-04-29 15:35 UTC, Ravassee commented on apph-front/src/services/ImageService.ts
> +const API_URL = process.env['REACT_APP_API_URL'];
À corriger après ton rebase sur dev

2022-04-29 15:35 UTC, Ravassee commented on apph-front/src/services/TableService.tsx
> +class TableService {
T'as fait un service exprès pour ta table ? c'est des données concernant les photos, ça va dans le PhotoService.ts... si on faisant un service par page on s'en sortirai pas

2022-04-29 15:35 UTC, Ravassee commented on apph-front/src/services/TableService.tsx
> +        token: userInfos?.token
Attention ici : Ce système fonctionne si on met en place de la gestion d'erreur dans le back, dans le cas où on appelle une route sans fourni de token/avec un token invalide, et du coup le front redirigerai vers `/signIn`... si tu ne veux pas le faire, ça vaut le coup de faire une US pour faire ça

2022-04-29 15:35 UTC, Ravassee commented on apph-front/src/services/TableService.tsx
> +    const successFunction = (val: any) => {
évite d'utiliser le `any`: spécifie le type de ta val (même si moi aussi j'ai envie de faire du JS, mais bon...)

2022-04-29 15:35 UTC, Ravassee commented on apph-front/src/static/components/Table.tsx
> +      () => {}
Si je comprends bien ces deux lignes, tu ne fourni pas de fonction de succès ni d'échec ? Il faudrait que tu fasses de la gestion d'erreur dans ton code, au minimum.

Et si tu ne fourni pas de fonction, ça ne sert à rien de les appeler dans tes services

2022-04-29 15:39 UTC, MOMney commented on apph-back/src/main/java/com/viseo/apph/controller/AuthController.java
> +            String jws = Jwts.builder().claim("login", user.getLogin()).claim("id",user.getId()).setExpiration(new Date(System.currentTimeMillis() + 7_200_000)).signWith(key).compact();
front a juste besoin de firstname, lastname et login

2022-05-02 13:43 UTC, wassim-viseo commented on apph-back/src/main/java/com/viseo/apph/security/WebSecurityConfig.java
> +              //  .antMatcher("/photo/**")
Parce qu'on avait un problème de cross origin sinon

2022-05-02 14:01 UTC, baptiste-viseo commented on apph-back/src/main/java/com/viseo/apph/service/PhotoService.java
> +                    .setUrl("fake url"); //TODO RECUPERER LE VRAI URL
prend un verre d'eau, respire, ça va aller

2022-05-02 14:29 UTC, baptiste-viseo requested changes

2022-05-02 14:29 UTC, baptiste-viseo commented on apph-front/src/tests/components/Table.test.tsx
> +  });
```suggestion
  it('Tests array display when data are send', () => {
    //GIVEN
    triggerRequestSuccess(
      '[{"title": "photo1","description": "photo test 1","creationDate": "2022-04-29T12:50:27.973+00:00","shootingDate": "2022-04-29T12:50:27.973+00:00","size": 1200,"tags": "img","url": "fakes url"},{"title": "photo2","description": "photo test 2","creationDate": "1970-01-02T11:58:58.983+00:00","shootingDate": "2022-04-29T12:50:27.973+00:00","tags": "img2","url": "fake url"}] '
    );
    //WHEN
    render(<Table />);
    //THEN
    expect(screen.getByText(/photo test 1/)).toBeInTheDocument();
  });
```

2022-05-02 14:29 UTC, baptiste-viseo commented on apph-back/src/main/java/com/viseo/apph/security/WebSecurityConfig.java
> +              //  .antMatcher("/photo/**")
le commentaire fix un probleme de cross origin ?

2022-05-02 14:29 UTC, baptiste-viseo commented on apph-front/src/services/TableService.tsx
> +      for (let elt of val) {
```suggestion
      for (const elt of val) {
```

j'ai une erreur eslint qui me dit d'utiliser const ici, y'a aussi d'autre warning eslint dans ce fichier

2022-05-02 14:41 UTC, wassim-viseo commented on apph-back/src/main/java/com/viseo/apph/controller/AuthController.java
> +            String jws = Jwts.builder().claim("login", user.getLogin()).claim("id",user.getId()).setExpiration(new Date(System.currentTimeMillis() + 7_200_000)).signWith(key).compact();
ça permet au back d'identifier l'user (grace à l'id contenu dans le token) quand il reçoit le token du front

2022-05-02 14:43 UTC, wassim-viseo commented on apph-back/src/main/java/com/viseo/apph/controller/PhotoController.java
> +    static TokenManager tokenManager = new TokenManager() {};
Comme l'interface est seulement utilisé dans cette classe et contient seulement qu'une methode, je pense pas que ce soit une bonne idée de créer un fichier juste pour elle

2022-05-02 14:45 UTC, wassim-viseo commented on apph-front/src/services/ImageService.ts
> +const API_URL = process.env['REACT_APP_API_URL'];
J'ai retiré le const API_URL lors du merge vu qu'il n'est plus utilisé sur la branche dev

2022-05-02 14:53 UTC, wassim-viseo commented on apph-back/src/test/java/com/viseo/apph/controller/PhotoControllerTest.java
>      }
Je sais pas pourquoi il s'est retiré mais je l'ai réintégré

2022-05-02 14:54 UTC, wassim-viseo commented on apph-back/src/test/java/com/viseo/apph/service/PhotoServiceTest.java
> -    }
Je sais pas pourquoi il s'est retiré mais je l'ai réintégré

2022-05-02 14:55 UTC, wassim-viseo commented on apph-front/src/services/TableService.tsx
> +class TableService {
Il n'y a pas de photoService.tsx

2022-05-02 14:56 UTC, wassim-viseo commented on apph-front/src/services/TableService.tsx
> +        token: userInfos?.token
Avec les privates routes on ne devrait pas avoir ce problème non ?

2022-05-02 15:04 UTC, wassim-viseo commented on apph-back/src/main/java/com/viseo/apph/security/WebSecurityConfig.java
> +              //  .antMatcher("/photo/**")
Enfaite normalement il aurait fallut mettre cette ligne mais lorsqu'on la met on a un problème de cross origin

2022-05-02 15:04 UTC, wassim-viseo commented on apph-back/src/main/java/com/viseo/apph/security/WebSecurityConfig.java
> +              //  .antMatcher("/photo/**")
mais je vais supprimer la ligne dans le code

2022-05-03 08:37 UTC, alexandre-hu commented on apph-front/src/static/components/Table.tsx
> +        console.log('Affichage du tableau');
pourquoi le console log ici ?

2022-05-03 08:37 UTC, alexandre-hu commented on apph-front/src/static/components/Table.tsx
> +      setData,
tu peux directement appeler cette fonction dans ton handleSuccess en dessous.

2022-05-03 08:37 UTC, alexandre-hu commented on apph-front/src/services/TableService.tsx
> +class TableService {
Faudrai Rename en ImageService en PhotoService et mettre ta fonction la bas, car on avait dit de faire un service front par controller.

2022-05-03 08:38 UTC, alexandre-hu commented on apph-back/src/main/java/com/viseo/apph/controller/PhotoController.java
> +    static TokenManager tokenManager = new TokenManager() {};
Et cette interface faudra le modifier un peu et faudra quand même le sortir dans un fichier à part car plusieurs controller l'utilise (Folder et User)

2022-05-03 08:59 UTC, Ravassee commented on apph-front/src/services/TableService.tsx
> +        token: userInfos?.token
Oui, ce commentaire datais d'avant les privates routes ^^ Donc tout va bien

2022-05-03 08:59 UTC, Ravassee commented on apph-back/src/main/java/com/viseo/apph/controller/AuthController.java
> +            String jws = Jwts.builder().claim("login", user.getLogin()).claim("id",user.getId()).setExpiration(new Date(System.currentTimeMillis() + 7_200_000)).signWith(key).compact();
l'user s'identifie directement avec le login présent dans le token, donc pas besoin de mettre l'id. Donc au total dans le token il y a nom + prénom + login.

2022-05-03 08:59 UTC, Ravassee commented on apph-back/src/main/java/com/viseo/apph/controller/PhotoController.java
> +    public interface TokenManager{
En fait c'est la première tâche de l'US de refacto back de faire cette interface... donc il faut soit que tu la termines  et que tu l'exportes, soit que tu la laisses pour la carte de refacto back

2022-05-03 08:59 UTC, Ravassee commented on apph-front/src/static/components/Table.tsx
> +export default function DataTable() {
Renomme aussi le fichier : Table n'est pas assez explicite.
Je les appelerai PhotoTable perso, mais je te laisse choisir.

2022-05-03 08:59 UTC, Ravassee commented on apph-front/src/static/components/Table.tsx
> +      <DataGrid
C'est secondaire, mais si tu ajoutes un nouveau commit ça serait bien que tu centres le tableau, là c'est pas très beau ^^'

2022-05-03 08:59 UTC, Ravassee commented on apph-front/src/services/TableService.tsx
> +class TableService {
Pardon, ImageService.ts*.
Mais il ne faut pas que tu créées un service juste pour ça.

2022-05-03 08:59 UTC, Ravassee commented on apph-front/src/static/components/Header.tsx
> +      <AppBar position="relative">
Si le style était défini dans un dossier à part, il vaut mieux que tu suives la convention et que tu fasses pareil.

2022-05-03 08:59 UTC, Ravassee commented on apph-front/src/static/components/UploadImage.tsx
> +    <Box sx={{ m: 1 }}>
à nouveau c'est secondaire, mais le bouton "upload" n'est pas aligné avec "APPH"... c'est stressant 
![image](https://user-images.githubusercontent.com/47947666/166427799-124d690f-2ccb-4e66-8d97-ae7275149ff0.png)

2022-05-03 08:59 UTC, Ravassee commented on apph-front/src/utils/theme.ts
> -  },
C'est ici que tu dois mettre ton `position:relative` je pense.

2022-05-03 10:11 UTC, alexandre-hu commented on apph-front/src/static/components/UploadImage.tsx
> +    <Box sx={{ m: 1 }}>
après normalement c'est plus aligné sur la gauche en temps normal

2022-05-03 10:13 UTC, alexandre-hu commented on apph-front/src/utils/theme.ts
> -  },
non, on a testé le component material ui est prioritaire au theme, donc soit un met dans le component `position="relative"`, soit on met du `!important`

2022-05-03 12:32 UTC, wassim-viseo commented on apph-back/src/main/java/com/viseo/apph/controller/AuthController.java
> +            String jws = Jwts.builder().claim("login", user.getLogin()).claim("id",user.getId()).setExpiration(new Date(System.currentTimeMillis() + 7_200_000)).signWith(key).compact();
Oui mais je récupère l'id directement depuis le token dans certaine méthode car c'est plus simple pour moi sinon ça m'oblige à faire des jointures entre user et photo pour récupérer les photos d'un user

2022-05-03 12:35 UTC, baptiste-viseo approved these changes

2022-05-03 12:42 UTC, alexandre-hu commented on apph-back/src/main/java/com/viseo/apph/controller/TokenManager.java
> +    };
Normalement il n'y a plus l'id dans le token, du coup on récupère plutôt le login dans le token.

2022-05-03 12:55 UTC, Ravassee approved these changes

2022-05-03 13:54 UTC, baptiste-viseo approved these changes

2022-05-03 15:12 UTC, merged