Feature/apph 5 multiupload
mgermanicus/apph pull request #45
Opened 2022-05-12 09:50 UTC by ddahon

2022-05-19 12:46 UTC, MOMney commented on apph-front/src/static/components/UploadImage.tsx
> +          <></>
!! files[i] &&  (
          <UploadListItem status={status} file={files[i]} key={i} />
        )

2022-05-19 12:49 UTC, MOMney requested changes

2022-05-19 12:49 UTC, MOMney commented on apph-front/src/static/components/UploadImage.tsx
> +          <></>
`!! files[i] && (
          <UploadListItem status={status} file={files[i]} key={i} />
        )`

2022-05-19 13:42 UTC, alexandre-hu commented on apph-front/src/static/components/UploadImage.tsx
>  };
Faudrai peut être mettre ces components dans un fichier à part, dans un UploadList.tsx et UploadListItem.tsx

2022-05-23 13:23 UTC, alexandre-hu requested changes
Il faudrai que lorsqu'on upload les images, le bouton d'upload soit désactiver, car sinon on peut le spammer pour upload plusieurs fois les images pendant l'upload des précédents.
De plus faudrai soit fermer le modal après avoir complétement fini d'upload ou alors faudrai reset les champs après upload pour pas réupload les même fichier de nouveau avec les même nom lorsqu'on click sur le bouton d'upload.

2022-05-24 08:42 UTC, Ravassee commented on apph-front/src/static/components/UploadImage.tsx
> +                </Collapse>
Tu peux utiliser la snackBar à la place de cette partie je pense

2022-05-24 08:42 UTC, Ravassee commented on apph-front/src/static/components/UploadList.tsx
> +  );
```suggestion
  return (
    <>
      {files && statuses.map(
        (status, i) =>
          !!files[i] && (
            <UploadListItem status={status} file={files[i]} key={i} />
          )
      )}
    </>
  );
```

2022-05-24 15:02 UTC, wassim-viseo approved these changes

2022-05-24 15:44 UTC, alexandre-hu approved these changes

2022-05-30 14:41 UTC, merged