Feature/apph 130 delete photo
mgermanicus/apph pull request #49
Opened 2022-05-16 15:05 UTC by iattach

2022-05-16 15:27 UTC, alexandre-hu commented on apph-back/src/main/java/com/viseo/apph/controller/PhotoController.java
> +            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(new MessageResponse("Une erreur est survenue lors du téléchargement"));
```suggestion
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(new MessageResponse("Une erreur est survenue lors de la suppression"));
```

2022-05-16 15:27 UTC, alexandre-hu commented on apph-back/src/main/java/com/viseo/apph/service/PhotoService.java
> +                s3Dao.delete(photo.getId() + photo.getFormat());
le photo id est hasher maintenant dans le S3, du coup faudrai aussi le hasher pour la fonction de delete si on veut retrouver le fichier dans le S3

2022-05-16 15:27 UTC, alexandre-hu commented on apph-back/src/test/java/com/viseo/apph/PhotoTest.java
> +        Assert.assertTrue(responseEntity.getStatusCode().is2xxSuccessful());
si c'est une erreur alors le status code devrait être Unauthorized, c'est même très bizarre que ça soit successful alors que c'est une erreur.

2022-05-16 15:32 UTC, alexandre-hu commented on apph-front/src/static/components/PhotoTable.tsx
> +      </ButtonGroup>
Faudrai le mettre à l'extérieur du component, ce component là est seulement la table des photos, on pensait aussi à faire en sorte que PhotoTable soit utilisable ailleurs, du coup les buttons ne devraient pas être intégrer avec

2022-05-17 07:44 UTC, iattach commented on apph-back/src/test/java/com/viseo/apph/PhotoTest.java
> +        Assert.assertTrue(responseEntity.getStatusCode().is2xxSuccessful());
Pas vraiment, la méthode suppression peut supprimer plusieurs photos. S'il y a une centaine de photo, parmi eux, il y a la moitié qui n'appartient pas à cet user, l'erreur n'est pas propre pour ce state, car l'autre moitié a été supprimé avec succès. Donc, si des photos n'appartient pas à cet user, on ne traite pas. 
C'est le même concept que l'api S3, même s'il n'existe pas de fichier dans le S3. Si on veut supprimer, S3 va exécuter quand même la suppression, mais il ne pose pas une exception.

2022-05-17 08:22 UTC, Ravassee requested changes

2022-05-17 08:22 UTC, Ravassee commented on apph-back/src/main/java/com/viseo/apph/dto/PhotoRequest.java
> +    long[] ids;
Pas du tout explicite comme nom, ce sont des ids de quoi ? Précise si tu peux (même si je crois comprendre au vu de la PR que ce sont des ids de photos

2022-05-17 08:22 UTC, Ravassee commented on apph-front/src/App.tsx
> +  frFR
Pourquoi est-ce que tu as rajouté ça ? ça me semble être de l'internationalisation, ce n'est pas le sujet de ton US

2022-05-17 08:22 UTC, Ravassee commented on apph-front/src/services/PhotoService.ts
> +    const failFunction = (errorMessage: string) => {
En terme de nommage, la convention veut plutôt qu'on appelle ceci `errorFunction`

2022-05-17 08:22 UTC, Ravassee commented on apph-front/src/services/Server.ts
> +        });
L'erreur que tu catchs ici n'est-elle pas catchée de base par le bloc en dessous, dans le `else` ? 
![image](https://user-images.githubusercontent.com/47947666/168762282-f926193e-4896-4ad7-b469-8218cc0224e8.png)

2022-05-17 08:22 UTC, Ravassee commented on apph-front/src/static/components/AlertSnackbar.tsx
> +export const AlertSnackbar = ({ open, severity, message, onClose }: Props) => {
Si c'est une barre pour afficher les messages d'erreur, il faudrait plutôt la mettre dans le dossier `/utils` non ?

2022-05-17 08:22 UTC, Ravassee commented on apph-front/src/static/components/AlertSnackbar.tsx
> +    <Snackbar open={open} autoHideDuration={6000} onClose={handleSnackbarClose}>
Si tu peux, essaye de centrer la barre

2022-05-17 08:22 UTC, Ravassee commented on apph-front/src/static/components/DeleteImage.tsx
> +  const [severity, setSeverity] = useState<AlertColor>();
Je pense qu'il vaut mieux que ça soit la barre qui gère son état : tu devrais juste lui dire si elle doit s'ouvrir, et elle s'occupe elle-même de sa fermeture (ça nous permettra de l'importer plus facilement)

2022-05-17 08:22 UTC, Ravassee commented on apph-front/src/static/components/DeleteImage.tsx
> +    console.log(ids);
console.log à enlever

2022-05-17 08:22 UTC, Ravassee commented on apph-front/src/static/components/DeleteImage.tsx
> +        message="Si vous confirmez, vos photos seront définitivement effacés"
Je ne sais pas si c'est facilement faisable, sinon c'est pas grave, mais essaye de mettre le message de confirmation à droite, et le `annuler` à gauche, je crois que c'est fait comme ça normalement (en tout cas j'ai failli me tromper par réflexe quand j'ai ouvert la modal ^^')

2022-05-17 08:22 UTC, Ravassee commented on apph-front/src/static/pages/MyPhotoPage.tsx
> -      <UploadImage />
https://github.com/mgermanicus/apph/pull/49/files#r873870799 et du coup il faut remettre le bouton upload et le bouton supprimer ici

2022-05-17 08:22 UTC, Ravassee commented on apph-front/src/static/pages/MyPhotoPage.tsx
> -      <UploadImage />
https://github.com/mgermanicus/apph/pull/49/files#r873870799
Et du coup il faut que tu remettes l'upload et la suppression ici

2022-05-17 08:27 UTC, iattach commented on apph-front/src/static/components/DeleteImage.tsx
> +    console.log(ids);
```suggestion
```

2022-05-17 08:27 UTC, iattach commented on apph-front/src/static/pages/MyPhotoPage.tsx
> -      <UploadImage />
Commentaire répété

2022-05-17 08:29 UTC, iattach commented on apph-front/src/services/Server.ts
> +        });
Non, on a dit hier, l'erreur n'est pas catché en cas d'erreur de promise

2022-05-17 08:30 UTC, iattach commented on apph-front/src/App.tsx
> +  frFR
Refacto de front qui nécessite pas de créer un ticket dessus, donc, je fais ici ...

2022-05-17 08:40 UTC, iattach commented on apph-front/src/static/components/AlertSnackbar.tsx
> +export const AlertSnackbar = ({ open, severity, message, onClose }: Props) => {
Précisez-moi la différence entre /utils et /component, AlertSnackbar retourne une balise <Snackbar />, qui n'est pas une fonction ou une variable. Si comme le critère ici, on doit mettre aussi ConfirmationDialog et ErrorCard dans /utils non?

2022-05-17 09:57 UTC, baptiste-viseo commented on apph-back/src/main/java/com/viseo/apph/dto/PhotoRequest.java
> +    long[] ids;
Oui je pense qu'il faut soir rendre PhotoRequest plus générique en prenant tout le temps une liste ids dans ce cas tu supprime id  et la liste contient la plupart du temps 1 seul élément soit tu peut crée une autre request : PhotosRequest que ressemble a PhotoRequest mais qui est utilisé a chaque fois qu'on effectue des request sur plusieurs photos

2022-05-17 11:28 UTC, baptiste-viseo requested changes

2022-05-17 11:28 UTC, baptiste-viseo commented on apph-back/src/main/java/com/viseo/apph/service/PhotoService.java
> +                s3Dao.delete(s3Dao.hashString(String.valueOf(photo.getId())) + photo.getFormat());
Il faut rester cohérent avec le reste du S3dao donc lui passer un domain Photo et le laisser hasher le string. Je considère que le hashage  de l'url fait partie de la logique du stockage et non du traitement de nos données c'est pour ça que je ne l'ai pas mis dans le service;
J'ai fait d'autres commentaire avec les refacto a faire pour appliquer ce changement.
```suggestion
                s3Dao.delete(photo);
```

2022-05-17 11:28 UTC, baptiste-viseo commented on apph-back/src/main/java/com/viseo/apph/dao/S3Dao.java
> +    public String hashString(String string) {
```suggestion
    private String hashString(String string) {
```

cf : le commentaire dans PhotoRequest.java

2022-05-17 11:28 UTC, baptiste-viseo commented on apph-back/src/test/java/com/viseo/apph/PhotoTest.java
> +        verify(s3Dao, times(1)).delete(anyString());
```suggestion
        verify(s3Dao, times(1)).delete(any());
```

cf : commentaire dans PhotoRequest.java

2022-05-17 11:28 UTC, baptiste-viseo commented on apph-back/src/test/java/com/viseo/apph/PhotoTest.java
> +        verify(s3Dao, times(0)).delete(anyString());
```suggestion
        verify(s3Dao, times(0)).delete(any());
```

cf : commentaire dans PhotoRequest.java

2022-05-17 12:12 UTC, iattach commented on apph-front/src/services/PhotoService.ts
> +    const failFunction = (errorMessage: string) => {
résolu

2022-05-17 12:12 UTC, iattach commented on apph-front/src/services/PhotoService.ts
> +    return Server.request(URL, requestOptions, successFunction, failFunction);
```suggestion
    const errorFunction= (errorMessage: string) => {
      handleError(JSON.parse(errorMessage));
    };
    return Server.request(URL, requestOptions, successFunction, errorFunction);
```

2022-05-17 12:36 UTC, iattach commented on apph-front/src/static/components/DeleteImage.tsx
> +  const [severity, setSeverity] = useState<AlertColor>();
C'est les choses que j'ai fait, non? Par principe, la partie de la barre est caché par défaut, `snackbarOpen` donne justement un booléen qui indique l'ouverture de la barre.  Sa fermeture est gérée par attribut `onClose` dans `AlertSnackbar`.

2022-05-17 12:42 UTC, iattach commented on apph-front/src/static/components/DeleteImage.tsx
> +        message="Si vous confirmez, vos photos seront définitivement effacés"
C'est pas moi qui écrit ce dialog, mais Doryan et moi aime bien l'idée que  la confirmation à gauche, et le annuler à droite

2022-05-17 12:52 UTC, iattach commented on apph-back/src/main/java/com/viseo/apph/dto/PhotoRequest.java
> +    long[] ids;
Je prends l'idée PhotosRequest @Ravassee @baptiste-viseo

2022-05-17 13:16 UTC, iattach commented on apph-front/src/static/components/DeleteImage.tsx
> +        message="Si vous confirmez, vos photos seront définitivement effacés"
Ok, j'accepte par l'enquête

2022-05-17 13:18 UTC, baptiste-viseo commented on apph-back/src/test/java/com/viseo/apph/PhotoTest.java
> +        //verify(s3Dao, times(1)).delete(anyString());
y'a un commentaire la faut pas oublier de l'enlever avant de merge.
(ou remplacer anyString() par any() si on garde l'assert)

2022-05-17 13:21 UTC, iattach commented on apph-back/src/test/java/com/viseo/apph/PhotoTest.java
> +        //verify(s3Dao, times(1)).delete(anyString());
```suggestion
```

2022-05-17 14:54 UTC, baptiste-viseo approved these changes

2022-05-19 12:20 UTC, MOMney commented on apph-front/src/redux/slices/photoSlice.tsx
> +        ...photos
ça marche quand on désélectionne une photo ?

2022-05-19 12:23 UTC, MOMney approved these changes

2022-05-19 12:35 UTC, Ravassee commented on apph-front/src/static/components/AlertSnackbar.tsx
> +export const AlertSnackbar = ({ open, severity, message, onClose }: Props) => {
Haha bon argument, en effet ça peut rester dans /component

2022-05-19 12:37 UTC, Ravassee commented on apph-front/src/static/components/DeleteImage.tsx
> +  const [severity, setSeverity] = useState<AlertColor>();
En effet, j'avais mal compris ton code.

2022-05-19 12:37 UTC, Ravassee approved these changes

2022-05-19 13:31 UTC, alexandre-hu commented on apph-back/src/main/java/com/viseo/apph/service/PhotoService.java
> +                photoDao.deletePhoto(photo.getId());
Si tu as déjà get la photo avec `Photo photo = photoDao.getPhoto(id);` tu peux directement faire passer la photo dans les paramètre pour delete: `photoDao.deletePhoto(photo);`

2022-05-19 13:31 UTC, alexandre-hu commented on apph-back/src/main/java/com/viseo/apph/dao/PhotoDao.java
> +        em.remove(photo);
Si tu as déjà récupérer la photo dans le service tu peux directement mettre en paramètre la photo plutôt que l'id.
```suggestion
    public void deletePhoto(Photo photo) {
        em.remove(photo);
```

2022-05-19 13:31 UTC, alexandre-hu commented on apph-back/src/main/java/com/viseo/apph/service/PhotoService.java
> +                photoDao.deletePhoto(photo.getId());
```suggestion
                photoDao.deletePhoto(photo);
```

2022-05-19 13:31 UTC, alexandre-hu commented on apph-back/src/test/java/com/viseo/apph/PhotoTest.java
> +
```suggestion

```

2022-05-19 13:58 UTC, merged