[feature][APPH-22] download photos with zip
mgermanicus/apph pull request #63
Opened 2022-05-30 13:18 UTC by iattach

Ajouter bien `max-zip-size-mb=50` dans application-local.properties pour tester

2022-06-02 08:56 UTC, alexandre-hu commented on apph-back/src/main/java/com/viseo/apph/controller/PhotoController.java
> +            e.printStackTrace();
faudrai enlever le `printStackTrace`

2022-06-02 08:56 UTC, alexandre-hu commented on apph-back/src/main/java/com/viseo/apph/service/PhotoService.java
> +                .setTitle(photo.getTitle()).setCreationDate(photo.getCreationDate()).setSize(photo.getSize()).setTags(photo.getTags()).setDescription(photo.getDescription()).setShootingDate(photo.get
pourquoi mettre ça sur une seule ligne?
c'est moins lisible sur une seule ligne quand on a autant de setter

2022-06-02 08:56 UTC, alexandre-hu commented on apph-front/src/static/components/DownloadZip.tsx
> +        a.dispatchEvent(event);
c'est quoi exactement a ? 
Faudrait un nom de constante qui a du sens.

2022-06-02 08:56 UTC, alexandre-hu commented on apph-front/src/static/pages/MyPhotoPage.tsx
> +        <DeleteImage ids={selectedIds} />
pourquoi il y a 2 boutons delete ?

2022-06-02 09:00 UTC, iattach commented on apph-front/src/static/pages/MyPhotoPage.tsx
> +        <DeleteImage ids={selectedIds} />
```suggestion
        <DownloadZip ids={selectedIds} titleZip={'photos'} />
        <DeleteImage ids={selectedIds} setRefresh={setRefresh} />
```

2022-06-02 09:01 UTC, iattach commented on apph-back/src/main/java/com/viseo/apph/service/PhotoService.java
> +                .setTitle(photo.getTitle()).setCreationDate(photo.getCreationDate()).setSize(photo.getSize()).setTags(photo.getTags()).setDescription(photo.getDescription()).setShootingDate(photo.get
formateur interne automatique

2022-06-02 09:02 UTC, iattach commented on apph-back/src/main/java/com/viseo/apph/controller/PhotoController.java
> +            e.printStackTrace();
```suggestion
```

2022-06-02 09:03 UTC, iattach commented on apph-front/src/static/components/DownloadZip.tsx
> +        a.dispatchEvent(event);
HTML <a> Tag `https://www.w3schools.com/tags/tag_a.asp`

2022-06-02 09:38 UTC, Ravassee requested changes
J'ai une erreur 500 quand j'essaye de télécharger deux photos que je viens d'uploader... je peux te montrer si tu veux

2022-06-02 09:38 UTC, Ravassee commented on apph-back/src/main/java/com/viseo/apph/service/PhotoService.java
> +                throw new MaxSizeExceededException("Vous n'est pas autorisé à effectuer ce téléchargement qui dépasse la taille maximum autorisée de " + zipMaxSize + " Mo.");
C'est très long comme message d'erreur ^^
`Erreur: Taille maximale du ZIP dépassée` suffit je pense

2022-06-02 09:38 UTC, Ravassee commented on apph-front/src/static/components/DownloadZip.tsx
> +        a.dispatchEvent(event);
J'ai du mal à comprendre ce que fait cette partie du code...
Tu télécharges la photo en simulant un click sur un lien ? Il n'y a pas plus simple, genre renvoyer le zip directement au front pour le télécharger ?

2022-06-02 09:38 UTC, Ravassee commented on apph-front/src/static/pages/MyPhotoPage.tsx
> +        <DownloadZip ids={selectedIds} titleZip={'photos'} />
ça ne sert à rien de créer une props si tu lui donnes un string en clair

2022-06-02 10:14 UTC, iattach commented on apph-front/src/static/pages/MyPhotoPage.tsx
> +        <DownloadZip ids={selectedIds} titleZip={'photos'} />
En vue de l'utilisation pour les US suivants, par cette props, on peut donner aussi le nom de dossier comme le titre du zip au lieu de 'photos' toujours par défaut.

2022-06-02 10:20 UTC, iattach commented on apph-back/src/main/java/com/viseo/apph/service/PhotoService.java
> +                throw new MaxSizeExceededException("Vous n'est pas autorisé à effectuer ce téléchargement qui dépasse la taille maximum autorisée de " + zipMaxSize + " Mo.");
```suggestion
                throw new MaxSizeExceededException("Erreur: Taille maximale du ZIP dépassée.");
```

2022-06-02 10:21 UTC, iattach commented on apph-front/src/static/components/DownloadZip.tsx
> +        a.dispatchEvent(event);
S3 encode le byte array en base64, on a besoin d'ajouter un décodeur dans l'url pour télécharger.

2022-06-02 12:15 UTC, alexandre-hu commented on apph-front/src/static/components/DownloadZip.tsx
> +        a.dispatchEvent(event);
```suggestion
        const link = document.createElement('a');
        const event = new MouseEvent('click');
        link.href = imageBase64;
        link.download = photos.title + photos.format;
        link.dispatchEvent(event);
```
je propose quelque chose comme ça si ça te va ou alors `downloadLink` si on veut être plus précis.

2022-06-02 12:17 UTC, alexandre-hu approved these changes

2022-06-03 12:15 UTC, Ravassee approved these changes

2022-06-07 12:41 UTC, merged