Feature/apph 142 delete photo from folder
mgermanicus/apph pull request #72
Opened 2022-06-03 08:35 UTC by MOMney

2022-06-03 08:55 UTC, alexandre-hu requested changes

2022-06-03 08:55 UTC, alexandre-hu commented on apph-front/src/static/components/PhotoDetails.tsx
> +            message="Si vous confirmez, vos photos seront supprimer du dossier"
```suggestion
            message="Si vous confirmez, la photo sera supprimer du dossier"
```

2022-06-03 08:55 UTC, alexandre-hu commented on apph-back/src/main/java/com/viseo/apph/dao/PhotoDao.java
> +    }
normalement pour du update tu n'as pas besoin de faire une query Update,
Juste dans le service tu get la photo puis tu as juste a set les attribut.
Si tu veux un exemple tu peux regarder ma fonction `movePhotosToFolder` dans `PhotoService`

2022-06-03 08:55 UTC, alexandre-hu commented on apph-back/src/main/java/com/viseo/apph/controller/PhotoController.java
> +    }
Je pense que tu peux faire un API juste pour supprimer la photo du dossier plutôt que un API qui update la photo
Un autre Us fait déjà l'API sur l'update des infos du photo et mon coté j'ai aussi un API pour la modification du file

2022-06-03 10:04 UTC, Ravassee requested changes

2022-06-03 10:04 UTC, Ravassee commented on apph-back/src/main/java/com/viseo/apph/service/PhotoService.java
> +            return photoDao.updatePhotoInfo(photoRequest, null);
Je ne suis pas sûr de comprendre le but de ce test, mais si l'id `-1` signifie 'pas de dossier', tu pourrais tout aussi bien mettre le champ 'folder' de l'entité 'photo' à -1, plutôt que de faire ce test

2022-06-03 10:04 UTC, Ravassee commented on apph-front/src/static/components/PhotoDetails.tsx
> +  setSnackSeverity
Il va peut être falloir penser à regrouper les props dans des objets, ça commence à en faire vraiment beaucoup... et beaucoup de ces props sont optionnelles, y'a peut être moyen d'améliorer ça

2022-06-03 10:04 UTC, Ravassee commented on apph-front/src/static/components/PhotoDetails.tsx
> +                  Supprimer depuis le dossier
Dans l'idéal, pour plus de précision: 
```suggestion
                  `Supprimer du dossier ${folder_path}`
```

2022-06-03 10:04 UTC, Ravassee commented on apph-front/src/static/pages/MyPhotoPage.tsx
> +            photoId={0}
Si cette props est fixe, elle est inutile : écris directement l'id dans la requête

2022-06-07 09:42 UTC, alexandre-hu approved these changes

2022-06-08 14:52 UTC, Ravassee approved these changes

2022-06-08 15:31 UTC, merged