Refactor/apph 175 add tag style
mgermanicus/apph pull request #73
Opened 2022-06-03 10:58 UTC by iattach

2022-06-03 12:06 UTC, Ravassee requested changes

2022-06-03 12:06 UTC, Ravassee commented on apph-front/src/static/components/PhotoDetails.tsx
> +                    />
Il faudrait faire un petit travail sur le CSS:
     - Le Chip n'est pas vraiment aligné avec la ligne `Tags`, ce qui rend bizarrement
     - Il faudrait que les tags aient une couleur associée. Actuellement, le premier est bleu, le deuxième est violet... ça ne permet pas de les identifier facilement
     - Il faudrait décaler un peu la liste pour qu'il y ait le même espace entre le label en gras `Tags:` qu'entre chaque tags

2022-06-03 12:08 UTC, alexandre-hu approved these changes

2022-06-07 08:19 UTC, baptiste-viseo approved these changes

2022-06-07 08:21 UTC, Ravassee approved these changes

2022-06-07 10:13 UTC, merged