Feature/apph 6 drag and drop
mgermanicus/apph pull request #76
Opened 2022-06-10 15:15 UTC by Ravassee

2022-06-13 08:40 UTC, alexandre-hu approved these changes

2022-06-13 08:44 UTC, ddahon approved these changes

2022-06-13 09:04 UTC, iattach approved these changes

2022-06-15 09:00 UTC, ddahon approved these changes

2022-06-15 09:00 UTC, alexandre-hu requested changes

2022-06-15 09:00 UTC, alexandre-hu commented on apph-front/src/utils/translations/en/common.json
> +      "addImage": "Please at least one image"
```suggestion
      "addImage": "Please add at least one image"
```

2022-06-15 09:08 UTC, alexandre-hu approved these changes

2022-06-15 09:08 UTC, merged