Feature/apph 100 choose language
mgermanicus/apph pull request #78
Opened 2022-06-13 09:21 UTC by wassim-viseo

2022-06-13 14:01 UTC, alexandre-hu commented on apph-front/src/utils/translations/en/common.json
> +    "forgottenPassword": "Forgotten password ?",
je pense qu'on dit plus "Forgot password ?" plutôt

2022-06-13 14:01 UTC, alexandre-hu commented on apph-front/src/utils/translations/en/common.json
> +      "serverConnection": "Server connection failure"
je pense que c'est plus "failed" que "failure"

2022-06-13 14:01 UTC, alexandre-hu commented on apph-front/src/utils/translations/en/common.json
> +      "emailUsed": "Email already used",
c'est normalement "Email already in use"

2022-06-13 14:01 UTC, alexandre-hu commented on apph-front/src/utils/translations/en/common.json
> +    "passwordConfirmation": "Confirmation password",
je pense que ce serai plus logique de dire quelque chose du genre "Confirm your password" plutôt

2022-06-13 14:01 UTC, alexandre-hu commented on apph-front/src/utils/translations/en/common.json
> +      "notExist": "L'utilisateur n'existe pas"
Un anglais peut facilement comprendre cette phrase

2022-06-13 14:01 UTC, alexandre-hu commented on apph-front/src/utils/translations/en/common.json
> +    "lastModification": "Date of last modification",
Je pense qu'il y a plus simple comme façon de dire Date de dernière modification

2022-06-13 14:01 UTC, alexandre-hu commented on apph-front/src/utils/translations/en/common.json
> +    "confirmDeletePhoto": "If you confirm, the photo will be deleted from the folder",
cette phrase me semble bizarre je pense qu'il faudrai la changer un peu, que ce soit français ou anglais

2022-06-13 14:01 UTC, alexandre-hu commented on apph-front/src/utils/translations/en/common.json
> +    "successMove": "Moving the photos is finished.",
. . .

2022-06-13 14:01 UTC, alexandre-hu commented on apph-front/src/utils/translations/en/common.json
> +    "warningDeleting": "If you confirm, your photos will be permanently deleted",
Ici aussi je pense aussi qu'il faudrai changer la façon de le dire en français et anglais

2022-06-13 14:01 UTC, alexandre-hu commented on apph-front/src/utils/translations/en/common.json
> +    "successDelete": "Deletion successfully completed",
. . .

2022-06-13 14:01 UTC, alexandre-hu commented on apph-front/src/utils/translations/en/common.json
> +      "notFound": "Photo introuvable",
"introuvable" est un mot anglais ?

2022-06-13 14:01 UTC, alexandre-hu commented on apph-front/src/utils/translations/en/common.json
> +    "confirmDelete": "Do you confirm the deletion?",
phrase bizarre, pour moi en tout cas

2022-06-13 14:01 UTC, alexandre-hu commented on apph-front/src/utils/translations/en/common.json
> +    "add": "Ajouter",
I am français

2022-06-13 14:01 UTC, alexandre-hu commented on apph-front/src/utils/translations/en/common.json
> +    "big": "Big"
plus logique de parler de "Large" que de "Big"

2022-06-14 07:58 UTC, Ravassee commented on apph-front/src/utils/translations/en/common.json
> +      "notExist": "L'utilisateur n'existe pas"
ça dégage

2022-06-14 08:00 UTC, Ravassee commented on apph-front/src/utils/translations/en/common.json
> +    "lastModification": "Date of last modification",
`Last modification` suffit je pense (c'est implicite que c'est une date), ou `Modification date` sinon

2022-06-14 08:02 UTC, Ravassee commented on apph-front/src/utils/translations/en/common.json
> +    "successMove": "Moving the photos is finished.",
"Photo successfully moved"

2022-06-14 08:05 UTC, Ravassee commented on apph-front/src/utils/translations/en/common.json
> +    "confirmDeletePhoto": "If you confirm, the photo will be deleted from the folder",
Plutôt une phrase interrogative pour les modals de confirmation : 
"Do you really want to remove this photo from this folder ?"

2022-06-14 08:07 UTC, Ravassee commented on apph-front/src/utils/translations/en/common.json
> +    "warningDeleting": "If you confirm, your photos will be permanently deleted",
Plutôt une phrase interrogative pour les modals de confirmation :
"Are you sure about deleting this image ?"

2022-06-14 08:07 UTC, Ravassee commented on apph-front/src/utils/translations/en/common.json
> +    "successDelete": "Deletion successfully completed",
"Photo/Image successfully deleted"

2022-06-14 08:08 UTC, Ravassee commented on apph-front/src/utils/translations/en/common.json
> +      "notFound": "Photo introuvable",
ça dégage

2022-06-14 08:09 UTC, Ravassee commented on apph-front/src/utils/translations/en/common.json
> +    "warningDeleting": "If you confirm, your photos will be permanently deleted",
Ah moi j'aime bien, ça indique ce que va faire l'action

2022-06-14 08:10 UTC, Ravassee commented on apph-front/src/utils/translations/en/common.json
> +    "confirmDelete": "Do you confirm the deletion?",
"Are you sure about deleting these photos/images ?"

2022-06-14 09:34 UTC, iattach commented on apph-front/src/utils/translations/fr/common.json
> +      "notExist": "User does not exist"
This is not french

2022-06-14 09:34 UTC, iattach commented on apph-front/src/utils/translations/fr/common.json
> +      "error": "Error",
erreur

2022-06-14 10:02 UTC, Ravassee requested changes
Peut être faire un contexte pour donner accès à la méthode `t()` à tous les enfants, plutôt que d'importer la méthode dans chaque composant.

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/static/components/FilterSelector.tsx
> -const filterReducers = (state: IFilter[], action: filterActions) => {
Nononon, ça ça reste en dehors du composant ^^'

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/static/components/PhotoDetails.tsx
> +            <Tooltip title="Details">
Il faut que tu traduises ça : "Détails" et "Details"

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/en/common.json
> +    "forgottenPassword": "Forgotten password ?",
Oui, "Forgot your password ?" ou "Password forgotten ?" à la limite

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/en/common.json
> +    "noAccount": "You don't have an account yet? Register now!",
"No account yet ? Register !"

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/en/common.json
> +    "treatments": "My Treatments",
"My tasks" ou "My processings"

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/en/common.json
> +      "warning": "Warning",
Peut être que tu peux faire une catégorie à part, qui regroupe les erreurs générales ? Genre "global.warning" pour ça ?

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/en/common.json
> +    "title": "Title of the photo",
Aled... "Photo title", ou juste "Title"

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/en/common.json
> +    "failDelete": "An error occurred during deleting",
```suggestion
    "failDelete": "An error occurred during deletion",
```
ou

```suggestion
    "failDelete": "An error occurred while deleting",
```

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/en/common.json
> +    "forbidden": "The user does not have access to this action."
Cette erreur s'addresse à l'utilisateur, donc plutôt "This action is forbidden.", ou "You do not have the rights to do this."

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/en/common.json
> +      "upload": "An error occurred during the upload",
```suggestion
      "upload": "An error occurred while uploading",
```

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/en/common.json
> +      "reUpload": "An error occurred during the re-upload.",
Je pense que tu peux utiliser l'erreur `upload.error.upload` plutôt que d'en faire une nouvelle

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/en/common.json
> +    "manyUploads": "Your files have been uploaded",
```suggestion
    "manyUploadsSuccess": "Your files have been successfully uploaded",
```

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/en/common.json
> +    "successChange": "The change was successful.",
```suggestion
    "successChange": "File successfully changed.",
```

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/en/common.json
> +    "value": "Valeur",
```suggestion
    "value": "Value",
```

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/en/common.json
> +    "add": "add a filter",
```suggestion
    "add": "Add filter",
```

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/en/common.json
> +    "delete": "Delete a filter",
```suggestion
    "delete": "Delete filter",
```

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/en/common.json
> +      "addPayloadNaN": "Error in adding the filter: the payload is not a number",
```suggestion
      "addPayloadNaN": "Error while adding filter: payload is not a number",
```

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/en/common.json
> +      "deletePayloadNaN": "Error in deleting the filter: the payload is not a number",
```suggestion
      "deletePayloadNaN": "Error while deleting filter: payload is not a number",
```

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/en/common.json
> +      "idNotMatch": "Error in filter update: id does not match any existing filter",
```suggestion
      "idNotMatch": "Error while filter is updated: id does not match any existing filter",
```

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/en/common.json
> +    "big": "Big"
```suggestion
    "large": "Large"
```

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/fr/common.json
> +    "created": "Utilisateur crée"
```suggestion
    "created": "Utilisateur créé"
```

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/fr/common.json
> +      "notAuthenticated": "L'utilisateur n'est pas authentifié",
```suggestion
      "notAuthenticated": "L'utilisateur n'est pas connecté",
```

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/fr/common.json
> +      "loginAlreadyToken": "This login is already taken",
```suggestion
      "loginAlreadyToken": "Ce login est déjà utilisé",
```

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/fr/common.json
> +      "notExist": "User does not exist"
```suggestion
      "notExist": "Cet utilisateur n'existe pas"
```

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/fr/common.json
> +    "lastModification": "Date de dernière modification",
```suggestion
    "lastModification": "Date de la dernière modification",
```

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/fr/common.json
> +      "error": "Error",
```suggestion
      "error": "Erreur",
```

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/fr/common.json
> +      "nullFolder": "Folder est null !",
```suggestion
      "nullFolder": "Le dossier n'existe pas !",
```

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/fr/common.json
> +      "parentNotExist": "Dossier parent non existant.",
```suggestion
      "parentNotExist": "Le dossier parent n'existe pas.",
```

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/fr/common.json
> +      "warning": "Avertissement",
ça dépend des utilisation, mais peut être ça plutôt
```suggestion
      "warning": "Attention",
```

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/fr/common.json
> +    "edited": "Photo édité",
```suggestion
    "edited": "Photo éditée",
```

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/fr/common.json
> +    "download": "Télécharger photos",
```suggestion
    "download": "Télécharger les photos",
```

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/fr/common.json
> +    "warningDeleting": "Si vous confirmez, vos photos seront définitivement effacés",
```suggestion
    "warningDeleting": "Si vous confirmez, vos photos seront définitivement supprimées",
```

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/fr/common.json
> +    "forbidden": "L'utilisateur n'a pas accès à cette action."
```suggestion
    "forbidden": "L'utilisateur n'a pas la droit d'effectuer cette action."
```

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/fr/common.json
> +      "overSize": "La taille du fichier excède la limite maximale"
```suggestion
      "overSize": "Le fichier est trop volumineux"
```

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/fr/common.json
> +      "addPayloadNaN": "Erreur dans l'ajout du filtre: le payload n'est pas un nombre.",
```suggestion
      "addPayloadNaN": "Erreur lors de l'ajout du filtre.",
```

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/fr/common.json
> +      "deletePayloadNaN": "Erreur dans la suppression du filtre: le payload n'est pas un nombre",
```suggestion
      "deletePayloadNaN": "Erreur lors de la suppression du filtre.",
```

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/fr/common.json
> +      "idNotMatch": "Erreur dans la mise à jour du filtre : l'id ne correspond à aucun filtre existant",
```suggestion
      "idNotMatch": "Erreur lors de la mise à jour du filtre.",
```

2022-06-14 10:02 UTC, Ravassee commented on apph-front/src/utils/translations/fr/common.json
> +      "gestion": "Erreur dans la gestion du filtre"
```suggestion
      "gestion": "Erreur lors de la gestion du filtre"
```

2022-06-14 11:44 UTC, alexandre-hu commented on apph-front/src/utils/translations/fr/common.json
> +    "forbidden": "L'utilisateur n'a pas accès à cette action."
```suggestion
    "forbidden": "L'utilisateur n'a pas le droit d'effectuer cette action."
```

2022-06-14 13:46 UTC, Ravassee approved these changes

2022-06-14 13:52 UTC, alexandre-hu commented on apph-front/src/utils/translations/en/common.json
> +    "treatments": "My processings",
"My Processing"

2022-06-14 13:52 UTC, alexandre-hu commented on apph-front/src/utils/translations/en/common.json
> +    "successDelete": "Photo/Image successfully deleted",
Faudrai choisir entre photo ou image la

2022-06-14 13:52 UTC, alexandre-hu commented on apph-front/src/utils/translations/en/common.json
> +    "confirmDelete": "Are you sure about deleting these photos/images ?",
pareil faudrai choisir entre photo et image

2022-06-14 13:58 UTC, alexandre-hu approved these changes

2022-06-14 14:01 UTC, iattach approved these changes

2022-06-14 14:21 UTC, iattach requested changes
- Quand on choisit le EN, c'est encore en français
 ![image](https://user-images.githubusercontent.com/30409365/173599957-f2ff771e-89f9-4920-ad01-c7c35fd3734a.png)
- Ici, les options dans les trois points ne sont pas gérées
![image](https://user-images.githubusercontent.com/30409365/173600457-841c8cfd-d647-488c-83ae-197985d4f8b4.png)
- Bug d'affichage
![image](https://user-images.githubusercontent.com/30409365/173600680-727294a4-1639-458d-8611-b9e54a9858a1.png)

2022-06-15 06:55 UTC, iattach approved these changes

2022-06-15 07:48 UTC, merged