[chore][apph-83] add github workflow for backend test and linter/prettier
mgermanicus/apph pull request #8
Opened 2022-04-11 14:16 UTC by baptiste-viseo

2022-04-12 08:34 UTC, ddahon requested changes

2022-04-12 08:34 UTC, ddahon commented on apph-front/.eslintrc
> +    "linebreak-style": ["error", "unix"]
```suggestion
    "prettier/prettier": [
      "error",
      {
        "endOfLine": "auto"
      }
    ]
```

Avec cette config ça marche chez moi sans rien changer dans l'IDE

2022-04-12 15:28 UTC, alexandre-hu approved these changes

2022-04-13 07:53 UTC, MOMney approved these changes

2022-04-13 15:01 UTC, Ravassee commented on .github/workflows/linter.yml
> +        run: npm run prettier
Normalement tu as juste besoin de faire un `npm run prettier`, prettier est sensé suivre aussi les règles d'eslint.

Est-ce que c'est vraiment utile de faire un hook de pre-push pour les linter alors qu'ils sont déjà en hook de pre-commit ?

2022-04-13 15:05 UTC, baptiste-viseo commented on .github/workflows/linter.yml
> +        run: npm run prettier
```suggestion
      - name: Run prettier
        run: npm run prettier
```

2022-04-13 15:11 UTC, baptiste-viseo commented on .github/workflows/linter.yml
> +        run: npm run prettier
C'est pas un hook de pre-push c'est une vérification après le push ça permet voir que le linter passe sur cette branche depuis github (même si ça devrait être impossible du push un branche ou le linter passe pas avec le hook de pre-commit).
Je suis d'accord que c'est pas essentiel mais c'est une garantie de plus et ça coute pas grand chose

2022-04-13 15:13 UTC, Ravassee approved these changes

2022-04-13 15:15 UTC, merged