Feature/apph 48 download folder
mgermanicus/apph pull request #83
Opened 2022-06-14 14:10 UTC by iattach

2022-06-17 13:04 UTC, alexandre-hu approved these changes

2022-06-20 08:49 UTC, Ravassee requested changes

2022-06-20 08:49 UTC, Ravassee commented on apph-back/src/main/java/com/viseo/apph/controller/FolderController.java
> +    public ResponseEntity<IResponseDto> downloadZip(@RequestBody FolderRequest request) {
`downloadZip` c'est pas très précis comme nom de méthode (y'a plusieurs zippages dans le projet), peut être plutôt `downloadFolderToZip` ou quelque chose comme ça

2022-06-20 08:49 UTC, Ravassee commented on apph-back/src/main/java/com/viseo/apph/dao/S3Dao.java
> -        if (name != null) {
Pourquoi avoir retiré ce test ? Le nom ne peut pas être null ?

2022-06-20 08:49 UTC, Ravassee commented on apph-back/src/main/java/com/viseo/apph/dao/S3Dao.java
> -        if (file != null) {
Même question qu'au dessus

2022-06-20 08:49 UTC, Ravassee commented on apph-back/src/main/java/com/viseo/apph/dto/PhotosRequest.java
> -    }
Pourquoi enlever ces méthodes alors que tu conserves `titleZip` ? On en a pas besoin ?

2022-06-20 08:49 UTC, Ravassee commented on apph-back/src/main/java/com/viseo/apph/dao/S3Dao.java
> -        if (name != null) {
Ah je vois que tu l'as déplacé dans le FolderService

2022-06-20 08:49 UTC, Ravassee commented on apph-back/src/main/java/com/viseo/apph/service/FolderService.java
> +    public FolderResponse download(User user, FolderRequest folderRequest) throws UnauthorizedException, IOException, MaxSizeExceededException {
Idem, le nom de la méthode n'est pas très explicite.
Je propose `downloadFolderToZip`, ou juste `downloadFolder`  si tu trouves ça trop long

2022-06-20 08:49 UTC, Ravassee commented on apph-front/src/services/PhotoService.ts
> -    titleZip: string,
Pourquoi avoir retiré cette option ? ça signifie qu'on ne peut plus choisir le titre du zip ?

2022-06-20 08:49 UTC, Ravassee commented on apph-front/src/static/components/DownloadZip.tsx
> -  titleZip = 'photos'
Pas très fan de retirer cette fonctionnalité... Si tu choisis de réutiliser un composant, il ne faut pas que ton US enlève des fonctionnalités d'anciennes US

2022-06-20 08:49 UTC, Ravassee commented on apph-front/src/static/components/DisplayPhoto.tsx
> +                <DownloadZip ids={[parseInt(selectedFolder)]} isFolder={true} />
Il faudrait que le nom du bouton change en fonction d'où on est : Ici, on ne veut pas `télécharger les photos`, mis `télécharger le dossier`, ce n'est pas la même fonctionnalité

2022-06-20 09:14 UTC, iattach commented on apph-front/src/services/PhotoService.ts
> -    titleZip: string,
pas précisé dans le US,  et quand on télécharge n'import quoi en zip, le nom du zip est compliqué à décider, donc, j'ai supprimé et j'ai mis "APPH-<date>" comme le nom de zip, la même norme que Google Drive et One Drive.

2022-06-20 09:15 UTC, iattach commented on apph-front/src/static/components/DownloadZip.tsx
> -  titleZip = 'photos'
même commentaire qu'au dessus

2022-06-20 09:16 UTC, iattach commented on apph-back/src/main/java/com/viseo/apph/dto/PhotosRequest.java
> -    }
même commentaire que l'autre

2022-06-20 09:16 UTC, iattach commented on apph-back/src/main/java/com/viseo/apph/dao/S3Dao.java
> -        if (file != null) {
les "null"s sont catché par IOException, donc, c'est inutile de tester manuellement. Quand même j'essaie de tester les if null pour code coverage, ils ne sont pas passé dans les tests

2022-06-20 12:16 UTC, Ravassee approved these changes

2022-06-20 12:55 UTC, merged