Feature/apph 40 admin settings
mgermanicus/apph pull request #96
Opened 2022-06-24 15:28 UTC by MOMney

2022-06-28 12:59 UTC, wassim-viseo approved these changes

2022-06-29 08:32 UTC, Ravassee requested changes

2022-06-29 08:32 UTC, Ravassee commented on apph-back/src/main/java/com/viseo/apph/domain/Setting.java
> +    long downloadSize;
Je pense que ça vaudrait le coup que tu initialises ces valeurs du coup ?
```suggestion
    long uploadSize = 10 mb;
    long downloadSize = 15 mb;
```

2022-06-29 08:32 UTC, Ravassee commented on apph-front/src/services/SettingService.ts
> +    downloadSize: number,
Ces paramètres devraient être optionnels, non ? On peut changer la taille de l'upload, la taille du download, ou les deux....

2022-06-29 08:39 UTC, MOMney commented on apph-front/src/services/SettingService.ts
> +    downloadSize: number,
je passe les deux valeurs directement, ils seront initialisé avec les valeurs qui sont dans la db.
`const updateParameters = async () =>
    SettingService.updateSettings(
      uploadSize,
      downloadSize,
      () => setMessage('admin.setting.success.modifySuccess'),
      () => {
        setErrorOccured(true);
        setMessage('admin.setting.error.modifyFailed');
      }
    );`

2022-06-29 14:27 UTC, Ravassee approved these changes

2022-06-29 14:27 UTC, merged